trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.14.3'
  tfDirectory: '$(System.DefaultWorkingDirectory)/terraform'

stages:
  - stage: Validate
    jobs:
      - job: TerraformValidate
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(tfDirectory)
              backendServiceArm: 'ado_sc'
              backendAzureRmResourceGroupName: 'manual'
              backendAzureRmStorageAccountName: 'azuredevopsaks'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(tfDirectory)

  - stage: Plan
    dependsOn: Validate
    jobs:
      - job: TerraformPlan
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(terraformVersion)
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(tfDirectory)
              backendServiceArm: 'ado_sc'
              backendAzureRmResourceGroupName: 'manual'
              backendAzureRmStorageAccountName: 'azuredevopsaks'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(tfDirectory)
              environmentServiceName: 'ado_sc'

  # - stage: Apply
  #   dependsOn: Plan
  #   condition: succeeded()
  #   jobs:
  #     - deployment: TerraformApply
  #       environment: 'dev'
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: TerraformInstaller@0
  #                 inputs:
  #                   terraformVersion: $(terraformVersion)
                
  #               - task: TerraformCLI@1
  #                 inputs:
  #                   provider: 'azurerm'
  #                   command: 'init'
  #                   workingDirectory: $(tfDirectory)
  #                   backendServiceArm: 'ado_sc'
  #                   backendAzureRmResourceGroupName: 'manual'
  #                   backendAzureRmStorageAccountName: 'azuredevopsaks'
  #                   backendAzureRmContainerName: 'tfstate'
  #                   backendAzureRmKey: 'terraform.tfstate'
                
  #               - task: TerraformCLI@1
  #                 inputs:
  #                   provider: 'azurerm'
  #                   command: 'apply'
  #                   workingDirectory: $(tfDirectory)
  #                   environmentServiceName: 'ado_sc'