trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.14.3'
  tfDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  azTenantId: 'd518e762-52b9-4009-9cb3-b09b9f5163a6'
  azServiceConnection: 'ado_sc'
  azStorageAccount: 'azuredevopsaks'
  azResourceGroup: 'manual'
  azContainerName: 'tfstate'
  tfStateFile: 'terraform.tfstate'

stages:
  - stage: Validate
    jobs:
      - job: TerraformValidate
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(tfDirectory)
              backendServiceArm: $(azServiceConnection)
              backendAzureRmTenantId: $(azTenantId)
              backendAzureRmResourceGroupName: '$(azResourceGroup)'
              backendAzureRmStorageAccountName: '$(azStorageAccount)'
              backendAzureRmContainerName: '$(azContainerName)'
              backendAzureRmKey: '$(tfStateFile)'
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(tfDirectory)

  - stage: Plan
    dependsOn: Validate
    jobs:
      - job: TerraformPlan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: $(terraformVersion)
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(tfDirectory)
              backendServiceArm: $(azServiceConnection)
              backendAzureRmTenantId: $(azTenantId)
              backendAzureRmResourceGroupName: $(azResourceGroup)
              backendAzureRmStorageAccountName: $(azStorageAccount)
              backendAzureRmContainerName: $(azContainerName)
              backendAzureRmKey: $(tfStateFile)
          
          - task: TerraformCLI@1
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(tfDirectory)
              environmentServiceName: $(azServiceConnection)

  # - stage: Apply
  #   dependsOn: Plan
  #   condition: succeeded()
  #   jobs:
  #     - deployment: TerraformApply
  #       environment: 'dev'
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: TerraformInstaller@1
  #                 inputs:
  #                   terraformVersion: $(terraformVersion)
                
  #               - task: TerraformCLI@1
  #                 inputs:
  #                   provider: 'azurerm'
  #                   command: 'init'
  #                   workingDirectory: $(tfDirectory)
  #                   backendServiceArm: 'ado_sc'
  #                   backendAzureRmTenantId: 'd518e762-52b9-4009-9cb3-b09b9f5163a6'
  #                   backendAzureRmResourceGroupName: 'manual'
  #                   backendAzureRmStorageAccountName: 'azuredevopsaks'
  #                   backendAzureRmContainerName: 'tfstate'
  #                   backendAzureRmKey: 'terraform.tfstate'
                
  #               - task: TerraformCLI@1
  #                 inputs:
  #                   provider: 'azurerm'
  #                   command: 'apply'
  #                   workingDirectory: $(tfDirectory)
  #                   environmentServiceName: 'ado_sc'