trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'terraform/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.14.3'
  workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  azServiceConnection: 'ado_sc'
  backendResourceGroup: 'manual'
  backendStorageAccount: 'azuredevopsaks'
  backendContainer: 'tfstate'
  backendKey: 'terraform.tfstate'

stages:
- stage: Validate
  jobs:
  - job: TerraformValidate
    steps:
    - checkout: self
    
    # - task: TerraformInstaller@1
    #   displayName: 'Install Terraform'
    #   inputs:
    #     terraformVersion: $(terraformVersion)
    
    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: $(azServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(workingDirectory)
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_TENANT_ID=$tenantId
          
          terraform init \
            -backend-config="resource_group_name=$(backendResourceGroup)" \
            -backend-config="storage_account_name=$(backendStorageAccount)" \
            -backend-config="container_name=$(backendContainer)" \
            -backend-config="key=$(backendKey)"
    
    - task: AzureCLI@2
      displayName: 'Terraform Validate'
      inputs:
        azureSubscription: $(azServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(workingDirectory)
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_TENANT_ID=$tenantId
          
          terraform validate
    
    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: $(azServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(workingDirectory)
        addSpnToEnvironment: true
        inlineScript: |
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_TENANT_ID=$tenantId
          
          terraform plan -out=tfplan

# - stage: Deploy
#   dependsOn: Validate
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
#   jobs:
#   - deployment: TerraformApply
#     environment: 'dev'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - checkout: self
          
#           - task: TerraformInstaller@1
#             displayName: 'Install Terraform'
#             inputs:
#               terraformVersion: $(terraformVersion)
          
#           - task: AzureCLI@2
#             displayName: 'Terraform Init'
#             inputs:
#               azureSubscription: $(azServiceConnection)
#               scriptType: 'bash'
#               scriptLocation: 'inlineScript'
#               workingDirectory: $(workingDirectory)
#               addSpnToEnvironment: true
#               inlineScript: |
#                 export ARM_CLIENT_ID=$servicePrincipalId
#                 export ARM_CLIENT_SECRET=$servicePrincipalKey
#                 export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#                 export ARM_TENANT_ID=$tenantId
                
#                 terraform init \
#                   -backend-config="resource_group_name=$(backendResourceGroup)" \
#                   -backend-config="storage_account_name=$(backendStorageAccount)" \
#                   -backend-config="container_name=$(backendContainer)" \
#                   -backend-config="key=$(backendKey)"
          
#           - task: AzureCLI@2
#             displayName: 'Terraform Apply'
#             inputs:
#               azureSubscription: $(azServiceConnection)
#               scriptType: 'bash'
#               scriptLocation: 'inlineScript'
#               workingDirectory: $(workingDirectory)
#               addSpnToEnvironment: true
#               inlineScript: |
#                 export ARM_CLIENT_ID=$servicePrincipalId
#                 export ARM_CLIENT_SECRET=$servicePrincipalKey
#                 export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#                 export ARM_TENANT_ID=$tenantId
                
#                 terraform apply -auto-approve
